// <auto-generated />
using System;
using Infra.DAO.ORM;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Infra.DAO.ORM.Migrations
{
    [DbContext(typeof(Rech_a_carDbContext))]
    [Migration("20211017053435_agora_ta_pica")]
    partial class agora_ta_pica
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.10")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Dominio.AluguelModule.Aluguel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ClienteId")
                        .HasColumnType("int");

                    b.Property<int?>("CupomId")
                        .HasColumnType("int");

                    b.Property<int?>("DadosCondutorId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataAluguel")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataDevolucao")
                        .HasColumnType("datetime2");

                    b.Property<int?>("FuncionarioId")
                        .HasColumnType("int");

                    b.Property<int>("TipoPlano")
                        .HasColumnType("int");

                    b.Property<int?>("VeiculoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("CupomId");

                    b.HasIndex("DadosCondutorId");

                    b.HasIndex("FuncionarioId");

                    b.HasIndex("VeiculoId");

                    b.ToTable("TBAluguel");
                });

            modelBuilder.Entity("Dominio.AluguelModule.RelatorioAluguel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AluguelId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DataEnvio")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("StreamAttachment")
                        .HasColumnType("varbinary(max)");

                    b.HasKey("Id");

                    b.HasIndex("AluguelId");

                    b.ToTable("TBEnvioRelatorio");
                });

            modelBuilder.Entity("Dominio.CupomModule.Cupom", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DataValidade")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("VARCHAR(30)");

                    b.Property<int?>("ParceiroId")
                        .HasColumnType("int");

                    b.Property<int>("Usos")
                        .HasColumnType("int");

                    b.Property<double>("ValorFixo")
                        .HasColumnType("float");

                    b.Property<double>("ValorMinimo")
                        .HasColumnType("float");

                    b.Property<int>("ValorPercentual")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ParceiroId");

                    b.ToTable("TBCupom");
                });

            modelBuilder.Entity("Dominio.Entities.PessoaModule.Condutor.DadosCondutor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.HasKey("Id");

                    b.ToTable("TBDadosCondutor");
                });

            modelBuilder.Entity("Dominio.Entities.PessoaModule.Condutor.Multa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("DadosCondutorId")
                        .HasColumnType("int");

                    b.Property<string>("Resumo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DadosCondutorId");

                    b.ToTable("TBMulta");
                });

            modelBuilder.Entity("Dominio.Entities.PessoaModule.SenhaHashed", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasColumnType("VARCHAR(MAX)");

                    b.Property<byte[]>("Salt")
                        .IsRequired()
                        .HasColumnType("VARBINARY(MAX)");

                    b.HasKey("Id");

                    b.ToTable("TBSenha");
                });

            modelBuilder.Entity("Dominio.ParceiroModule.Parceiro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("VARCHAR(80)");

                    b.HasKey("Id");

                    b.ToTable("TBParceiro");
                });

            modelBuilder.Entity("Dominio.PessoaModule.Pessoa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Documento")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Endereco")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("VARCHAR(80)");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasColumnType("CHAR(11)");

                    b.Property<string>("TipoPessoa")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TBPessoa");
                });

            modelBuilder.Entity("Dominio.ServicoModule.Servico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AluguelId")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("VARCHAR(80)");

                    b.Property<double>("Taxa")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("AluguelId");

                    b.ToTable("TBServico");
                });

            modelBuilder.Entity("Dominio.VeiculoModule.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("VARCHAR(80)");

                    b.Property<double>("PrecoDiaria")
                        .HasColumnType("FLOAT");

                    b.Property<double>("PrecoKm")
                        .HasColumnType("FLOAT");

                    b.Property<double>("PrecoLivre")
                        .HasColumnType("FLOAT");

                    b.Property<int>("QuilometragemFranquia")
                        .HasColumnType("INT");

                    b.Property<int>("TipoDeCnh")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("TBCategoria");
                });

            modelBuilder.Entity("Dominio.VeiculoModule.Veiculo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Ano")
                        .HasColumnType("int");

                    b.Property<bool>("Automatico")
                        .HasColumnType("bit");

                    b.Property<int>("Capacidade")
                        .HasColumnType("int");

                    b.Property<int>("CapacidadeTanque")
                        .HasColumnType("int");

                    b.Property<int?>("CategoriaId")
                        .HasColumnType("int");

                    b.Property<string>("Chassi")
                        .IsRequired()
                        .HasColumnType("CHAR(17)");

                    b.Property<byte[]>("Foto")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasColumnType("VARCHAR(30)");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasColumnType("VARCHAR(30)");

                    b.Property<string>("Placa")
                        .IsRequired()
                        .HasColumnType("CHAR(7)");

                    b.Property<int>("Porta_malas")
                        .HasColumnType("int");

                    b.Property<int>("Portas")
                        .HasColumnType("int");

                    b.Property<int>("Quilometragem")
                        .HasColumnType("int");

                    b.Property<int>("TipoDeCombustivel")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.ToTable("TBVeiculo");
                });

            modelBuilder.Entity("Dominio.PessoaModule.ClienteModule.Cliente", b =>
                {
                    b.HasBaseType("Dominio.PessoaModule.Pessoa");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("VARCHAR(80)");

                    b.ToTable("TBCliente");
                });

            modelBuilder.Entity("Dominio.PessoaModule.Funcionario", b =>
                {
                    b.HasBaseType("Dominio.PessoaModule.Pessoa");

                    b.Property<int>("Cargo")
                        .HasColumnType("int");

                    b.Property<byte[]>("Foto")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Usuario")
                        .IsRequired()
                        .HasColumnType("VARCHAR(30)");

                    b.ToTable("TBFuncionario");
                });

            modelBuilder.Entity("Dominio.PessoaModule.Motorista", b =>
                {
                    b.HasBaseType("Dominio.PessoaModule.Pessoa");

                    b.Property<int?>("DadosCondutorId")
                        .HasColumnType("int");

                    b.Property<int?>("EmpresaId")
                        .HasColumnType("int");

                    b.HasIndex("DadosCondutorId");

                    b.HasIndex("EmpresaId");

                    b.ToTable("TBMotorista");
                });

            modelBuilder.Entity("Dominio.PessoaModule.ClienteModule.ClientePF", b =>
                {
                    b.HasBaseType("Dominio.PessoaModule.ClienteModule.Cliente");

                    b.Property<int?>("DadosCondutorId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnType("datetime2");

                    b.HasIndex("DadosCondutorId");

                    b.ToTable("TBClientePF");
                });

            modelBuilder.Entity("Dominio.PessoaModule.ClienteModule.ClientePJ", b =>
                {
                    b.HasBaseType("Dominio.PessoaModule.ClienteModule.Cliente");

                    b.ToTable("TBClientePJ");
                });

            modelBuilder.Entity("Dominio.AluguelModule.Aluguel", b =>
                {
                    b.HasOne("Dominio.PessoaModule.ClienteModule.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId");

                    b.HasOne("Dominio.CupomModule.Cupom", "Cupom")
                        .WithMany()
                        .HasForeignKey("CupomId");

                    b.HasOne("Dominio.Entities.PessoaModule.Condutor.DadosCondutor", "DadosCondutor")
                        .WithMany()
                        .HasForeignKey("DadosCondutorId");

                    b.HasOne("Dominio.PessoaModule.Funcionario", "Funcionario")
                        .WithMany()
                        .HasForeignKey("FuncionarioId");

                    b.HasOne("Dominio.VeiculoModule.Veiculo", "Veiculo")
                        .WithMany()
                        .HasForeignKey("VeiculoId");

                    b.Navigation("Cliente");

                    b.Navigation("Cupom");

                    b.Navigation("DadosCondutor");

                    b.Navigation("Funcionario");

                    b.Navigation("Veiculo");
                });

            modelBuilder.Entity("Dominio.AluguelModule.RelatorioAluguel", b =>
                {
                    b.HasOne("Dominio.AluguelModule.Aluguel", "Aluguel")
                        .WithMany()
                        .HasForeignKey("AluguelId");

                    b.Navigation("Aluguel");
                });

            modelBuilder.Entity("Dominio.CupomModule.Cupom", b =>
                {
                    b.HasOne("Dominio.ParceiroModule.Parceiro", "Parceiro")
                        .WithMany()
                        .HasForeignKey("ParceiroId");

                    b.Navigation("Parceiro");
                });

            modelBuilder.Entity("Dominio.Entities.PessoaModule.Condutor.DadosCondutor", b =>
                {
                    b.OwnsOne("Dominio.PessoaModule.Condutor.CNH", "Cnh", b1 =>
                        {
                            b1.Property<int>("DadosCondutorId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int")
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<int>("Id")
                                .HasColumnType("int");

                            b1.Property<string>("NumeroCnh")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<int>("TipoCnh")
                                .HasColumnType("int");

                            b1.HasKey("DadosCondutorId");

                            b1.ToTable("TBDadosCondutor");

                            b1.WithOwner()
                                .HasForeignKey("DadosCondutorId");
                        });

                    b.Navigation("Cnh");
                });

            modelBuilder.Entity("Dominio.Entities.PessoaModule.Condutor.Multa", b =>
                {
                    b.HasOne("Dominio.Entities.PessoaModule.Condutor.DadosCondutor", null)
                        .WithMany("Multas")
                        .HasForeignKey("DadosCondutorId");
                });

            modelBuilder.Entity("Dominio.ServicoModule.Servico", b =>
                {
                    b.HasOne("Dominio.AluguelModule.Aluguel", "Aluguel")
                        .WithMany("Servicos")
                        .HasForeignKey("AluguelId");

                    b.Navigation("Aluguel");
                });

            modelBuilder.Entity("Dominio.VeiculoModule.Veiculo", b =>
                {
                    b.HasOne("Dominio.VeiculoModule.Categoria", "Categoria")
                        .WithMany()
                        .HasForeignKey("CategoriaId");

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("Dominio.PessoaModule.ClienteModule.Cliente", b =>
                {
                    b.HasOne("Dominio.PessoaModule.Pessoa", null)
                        .WithOne()
                        .HasForeignKey("Dominio.PessoaModule.ClienteModule.Cliente", "Id")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Dominio.PessoaModule.Funcionario", b =>
                {
                    b.HasOne("Dominio.PessoaModule.Pessoa", null)
                        .WithOne()
                        .HasForeignKey("Dominio.PessoaModule.Funcionario", "Id")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Dominio.PessoaModule.Motorista", b =>
                {
                    b.HasOne("Dominio.Entities.PessoaModule.Condutor.DadosCondutor", "DadosCondutor")
                        .WithMany()
                        .HasForeignKey("DadosCondutorId");

                    b.HasOne("Dominio.PessoaModule.ClienteModule.ClientePJ", "Empresa")
                        .WithMany("Motoristas")
                        .HasForeignKey("EmpresaId");

                    b.HasOne("Dominio.PessoaModule.Pessoa", null)
                        .WithOne()
                        .HasForeignKey("Dominio.PessoaModule.Motorista", "Id")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.Navigation("DadosCondutor");

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("Dominio.PessoaModule.ClienteModule.ClientePF", b =>
                {
                    b.HasOne("Dominio.Entities.PessoaModule.Condutor.DadosCondutor", "DadosCondutor")
                        .WithMany()
                        .HasForeignKey("DadosCondutorId");

                    b.HasOne("Dominio.PessoaModule.ClienteModule.Cliente", null)
                        .WithOne()
                        .HasForeignKey("Dominio.PessoaModule.ClienteModule.ClientePF", "Id")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.Navigation("DadosCondutor");
                });

            modelBuilder.Entity("Dominio.PessoaModule.ClienteModule.ClientePJ", b =>
                {
                    b.HasOne("Dominio.PessoaModule.ClienteModule.Cliente", null)
                        .WithOne()
                        .HasForeignKey("Dominio.PessoaModule.ClienteModule.ClientePJ", "Id")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Dominio.AluguelModule.Aluguel", b =>
                {
                    b.Navigation("Servicos");
                });

            modelBuilder.Entity("Dominio.Entities.PessoaModule.Condutor.DadosCondutor", b =>
                {
                    b.Navigation("Multas");
                });

            modelBuilder.Entity("Dominio.PessoaModule.ClienteModule.ClientePJ", b =>
                {
                    b.Navigation("Motoristas");
                });
#pragma warning restore 612, 618
        }
    }
}
