CREATE TABLE [dbo].[TBAluguel] (
    [ID]               INT        IDENTITY (1, 1) NOT NULL,
    [ID_VEICULO]       INT        NOT NULL,
    [TIPO_PLANO]       INT        NOT NULL,
    [DATA_ALUGUEL]     DATETIME   NOT NULL,
    [DATA_DEVOLUCAO]   DATETIME   NOT NULL,
    [ID_CLIENTE]       INT        NOT NULL,
    [ID_CONDUTOR]      INT        NOT NULL,
    [ID_FUNCIONARIO]   INT        NOT NULL,
    [DATA_DEVOLVIDA]   DATETIME   NULL,
    [KM_RODADOS]       INT        NULL,
    [TANQUE_UTILIZADO] FLOAT (53) NULL,
    [TOTAL]            FLOAT (53) NULL,
    CONSTRAINT [PK_TBAluguel] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_TBAluguel_TBFuncionario] FOREIGN KEY ([ID_FUNCIONARIO]) REFERENCES [dbo].[TBFuncionario] ([ID]) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT [FK_TBAluguel_TBVeiculo] FOREIGN KEY ([ID_VEICULO]) REFERENCES [dbo].[TBVeiculo] ([ID]) ON DELETE CASCADE ON UPDATE CASCADE
);

