CREATE TABLE [dbo].[TBClientePJ] (
    [ID]        INT           IDENTITY (1, 1) NOT NULL,
    [NOME]      VARCHAR (50)  NOT NULL,
    [TELEFONE]  VARCHAR (50)  NOT NULL,
    [ENDERECO]  VARCHAR (50)  NOT NULL,
    [DOCUMENTO] VARCHAR (50)  NOT NULL,
    [EMAIL]     VARCHAR (100) NOT NULL,
    CONSTRAINT [PK_TBClientePJ] PRIMARY KEY CLUSTERED ([ID] ASC)
);

